- name: Install some basic apt packages
  ansible.builtin.apt:
    name:
      - bash-completion
      - curl
      - hstr
      - python3
      - python3-pip
      - python-is-python3
      - jq
  become: true
  tags: [personal, work]
