---
repositories:
  - url: https://download.docker.com/linux/ubuntu/gpg
    dest: docker.asc
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] \
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker

  - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: kubernetes-archive-keyring.gpg
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes

  - url: https://apt.releases.hashicorp.com/gpg
    dest: hashicorp-archive-keyring.asc
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] \
          https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp

  - url: https://packages.microsoft.com/keys/microsoft.asc
    dest: microsoft.asc
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/microsoft.asc] \
          https://packages.microsoft.com/repos/code stable main"
    filename: vscode

  - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: cloud.google.gpg
    repo: "deb [signed-by=/etc/apt/keyrings/cloud.google.gpg] \
          https://packages.cloud.google.com/apt cloud-sdk main"
    filename: google-cloud-sdk